export const API = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh",
    ME: "/auth/me",
    VERIFY_EMAIL_TOKEN: (token: string) => `/auth/verify-email/${token}`,
    VERIFY_EMAIL_CODE: "/auth/verify-email",
    REQUEST_RESET: "/auth/request-password-reset",
    RESET_PASSWORD: (token: string) => `/auth/reset-password/${token}`,
    RESET_PASSWORD_CODE: "/auth/reset-password",
    MFA_SETUP: "/auth/mfa/setup",
    MFA_CONFIRM: "/auth/mfa/confirm",
  },
  COURSES: {
    LIST: "/courses",
    DETAIL: (slug: string) => `/courses/${slug}`,
  },
  PROFILE: {
    GET: "/profile",
    UPDATE: "/profile",
    CHANGE_PASSWORD: "/profile/change-password",
    EXPORT: "/profile/export",
  },
  PAYMENTS: {
    CREATE_INTENT: "/payments/create-intent",
    MY_TRANSACTIONS: "/payments/my-transactions",
  },
  ADMIN: {
    STATS: "/admin/stats",
    USERS: "/admin/users",
    TOGGLE_USER: (id: string) => `/admin/users/${id}/toggle-active`,
    DELETE_USER: (id: string) => `/admin/users/${id}`,
    LOGS: "/admin/logs",
    COURSES: "/admin/courses",
    CREATE_COURSE: "/admin/courses",
    UPDATE_COURSE: (id: string) => `/admin/courses/${id}`,
    DELETE_COURSE: (id: string) => `/admin/courses/${id}`,
    ADD_LESSON: (id: string) => `/admin/courses/${id}/lessons`,
    TRANSACTIONS: "/admin/transactions",
  },
};
